name: Lint
description: Run ESLint and tests on pull requests to the main branch

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: pnpm install
      - run: pnpm test
